-d C:\ASIER\00-Electronica\U1-FPGAs\Proyecto\src\Gowin_Project\impl\gwsynthesis\Gowin_Project.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst C:\ASIER\00-Electronica\U1-FPGAs\Proyecto\src\Gowin_Project\src\Gowin_Project.cst
-cfg C:\ASIER\00-Electronica\U1-FPGAs\Proyecto\src\Gowin_Project\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
